import Link from "next/link";
import { redirect } from "next/navigation";
import { ClipboardPenLine } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { getSessionUser } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import type { Tarea } from "@/lib/supabase/database.types";
export const dynamic="force-dynamic";
export default async function MisEntregasPage(){const user=await getSessionUser();if(!user)redirect("/login?redirect=/mis-entregas");const supabase=await createClient();let tasks:(Pick<Tarea,"id"|"titulo"|"fecha_limite"|"puntaje_maximo">&{cursos:{titulo:string}|null})[]=[];if(supabase){const{data}=await supabase.from("tareas").select("id,titulo,fecha_limite,puntaje_maximo,cursos(titulo)").eq("publicada",true).order("fecha_limite",{ascending:true});tasks=(data as typeof tasks|null)??[]}return <AppShell user={user}><div className="mx-auto max-w-4xl px-5 py-10 sm:px-8 sm:py-12"><div className="mb-8 flex items-start gap-3"><ClipboardPenLine className="mt-1 h-5 w-5" style={{color:"var(--primary)"}}/><div><p className="eyebrow" style={{color:"var(--primary)"}}>Trabajo aplicado</p><h1 className="mt-1 font-serif-brand text-3xl font-bold" style={{color:"var(--text)"}}>Mis entregas</h1></div></div><div className="card divide-y" style={{borderColor:"var(--border)"}}>{tasks.length===0?<p className="p-8 text-center text-sm" style={{color:"var(--text-muted)"}}>No tienes entregas pendientes.</p>:tasks.map(task=><Link key={task.id} href={`/entregas/${task.id}`} className="flex items-center justify-between gap-4 p-5 transition-colors hover:bg-[color:var(--surface-2)]"><div><p className="text-sm font-semibold" style={{color:"var(--text)"}}>{task.titulo}</p><p className="mt-1 text-xs" style={{color:"var(--text-faint)"}}>{task.cursos?.titulo??"Curso"} · {task.fecha_limite?new Intl.DateTimeFormat("es-CL",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(task.fecha_limite)):"Sin fecha límite"}</p></div><span className="text-xs font-semibold" style={{color:"var(--primary)"}}>Abrir</span></Link>)}</div></div></AppShell>}
