"use client";
import Link from "next/link";
import { useState } from "react";
import { ClipboardPenLine, Loader2, Plus } from "lucide-react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

export function TaskManager({ cursoId, basePath, tareas }: { cursoId: string; basePath: string; tareas: { id: string; titulo: string; fecha_limite: string | null; puntaje_maximo: number; publicada: boolean }[] }) {
  const router = useRouter(); const [form, setForm] = useState({ titulo: "", instrucciones: "", fecha: "", puntaje: "100", reentrega: true }); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  async function create(e: React.FormEvent) { e.preventDefault(); const supabase = createClient(); if (!supabase || !form.titulo.trim()) return; const { data: { user } } = await supabase.auth.getUser(); if (!user) return; setBusy(true); const { error } = await supabase.from("tareas").insert({ curso_id: cursoId, titulo: form.titulo.trim(), instrucciones: form.instrucciones.trim(), fecha_limite: form.fecha ? new Date(form.fecha).toISOString() : null, puntaje_maximo: Math.max(1, Number(form.puntaje) || 100), permitir_reentrega: form.reentrega, publicada: true, creado_por: user.id } as never); setBusy(false); if (error) { setError(error.message); return; } setForm({ titulo: "", instrucciones: "", fecha: "", puntaje: "100", reentrega: true }); router.refresh(); }
  return <div className="grid gap-5"><div className="card divide-y" style={{ borderColor: "var(--border)" }}>{tareas.length === 0 ? <p className="p-7 text-center text-sm" style={{ color: "var(--text-muted)" }}>Aún no hay entregas creadas.</p> : tareas.map((tarea) => <div key={tarea.id} className="flex items-center justify-between gap-4 p-4"><div><p className="text-sm font-semibold" style={{ color: "var(--text)" }}>{tarea.titulo}</p><p className="mt-1 text-xs" style={{ color: "var(--text-faint)" }}>{tarea.fecha_limite ? `Cierra ${new Intl.DateTimeFormat("es-CL", { dateStyle: "medium", timeStyle: "short" }).format(new Date(tarea.fecha_limite))}` : "Sin fecha límite"} · {tarea.puntaje_maximo} pts</p></div><Link href={`${basePath}/${tarea.id}`} className="btn-ghost rounded-lg px-3 py-2 text-xs">Revisar</Link></div>)}</div><form onSubmit={create} className="card p-5 sm:p-6"><div className="mb-4 flex items-center gap-2"><ClipboardPenLine className="h-4 w-4" style={{ color: "var(--primary)" }} /><h2 className="text-sm font-semibold" style={{ color: "var(--text)" }}>Nueva entrega</h2></div><div className="grid gap-3"><input required value={form.titulo} onChange={(e) => setForm({ ...form, titulo: e.target.value })} placeholder="Título: Informe de análisis" className="rounded-xl px-4 py-3 text-sm outline-none" style={{ background: "var(--surface-2)", border: "1px solid var(--border-strong)", color: "var(--text)" }} /><textarea value={form.instrucciones} onChange={(e) => setForm({ ...form, instrucciones: e.target.value })} rows={5} placeholder="Instrucciones, temario, criterios y formato esperado" className="rounded-xl px-4 py-3 text-sm outline-none" style={{ background: "var(--surface-2)", border: "1px solid var(--border-strong)", color: "var(--text)" }} /><div className="grid gap-3 sm:grid-cols-2"><input type="datetime-local" value={form.fecha} onChange={(e) => setForm({ ...form, fecha: e.target.value })} className="rounded-xl px-4 py-3 text-sm outline-none" style={{ background: "var(--surface-2)", border: "1px solid var(--border-strong)", color: "var(--text)" }} /><input type="number" min={1} value={form.puntaje} onChange={(e) => setForm({ ...form, puntaje: e.target.value })} placeholder="Puntaje máximo" className="rounded-xl px-4 py-3 text-sm outline-none" style={{ background: "var(--surface-2)", border: "1px solid var(--border-strong)", color: "var(--text)" }} /></div><label className="text-xs" style={{ color: "var(--text-muted)" }}><input type="checkbox" checked={form.reentrega} onChange={(e) => setForm({ ...form, reentrega: e.target.checked })} className="mr-2" />Permitir actualizar la entrega</label>{error && <p className="text-xs" style={{ color: "#dc2626" }}>{error}</p>}<button disabled={busy} className="btn-primary inline-flex w-fit items-center gap-2 rounded-lg px-4 py-3 text-xs disabled:opacity-60">{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />}Crear entrega</button></div></form></div>;
}
