"use client";
import { useState } from "react";
import { FileUp, Loader2, Send } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

export function TaskSubmitter({ tareaId, userId, initial }: { tareaId: string; userId: string; initial: { texto: string | null; enlace: string | null; archivo_path: string | null; estado: string; entregado_at: string } | null }) {
  const [texto, setTexto] = useState(initial?.texto ?? ""); const [enlace, setEnlace] = useState(initial?.enlace ?? ""); const [file, setFile] = useState<File | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  async function submit(e: React.FormEvent) {
    e.preventDefault(); if (!texto.trim() && !enlace.trim() && !file) { setMessage("Agrega un texto, enlace o archivo."); return; }
    const supabase = createClient(); if (!supabase) return; setBusy(true); setMessage(null); let archivoPath = initial?.archivo_path ?? null;
    if (file) { const clean = file.name.replace(/[^a-zA-Z0-9._-]/g, "-"); archivoPath = `${userId}/${tareaId}/${Date.now()}-${clean}`; const { error } = await supabase.storage.from("entregas").upload(archivoPath, file); if (error) { setBusy(false); setMessage("No se pudo subir el archivo. Revisa el tipo y tamaño (máx. 10 MB)."); return; } }
    try { const response = await fetch("/api/entregas/submit", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ tareaId, texto, enlace, archivoPath }) }); if (!response.ok) { const data = await response.json(); setMessage(data.error === "resubmission_disabled" ? "Esta entrega no permite reenvíos." : "No se pudo guardar tu entrega."); } else { setMessage("Entrega guardada correctamente."); } } catch { setMessage("No se pudo guardar tu entrega."); } finally { setBusy(false); }
  }
  return <form onSubmit={submit} className="card p-5 sm:p-6"><h2 className="text-sm font-semibold" style={{ color: "var(--text)" }}>{initial ? "Actualizar entrega" : "Enviar entrega"}</h2>{initial && <p className="mt-1 text-xs" style={{ color: "var(--text-faint)" }}>Último envío: {new Intl.DateTimeFormat("es-CL", { dateStyle: "medium", timeStyle: "short" }).format(new Date(initial.entregado_at))} · {initial.estado}</p>}<div className="mt-4 grid gap-3"><textarea value={texto} onChange={(e) => setTexto(e.target.value)} maxLength={12000} rows={7} placeholder="Escribe tu respuesta, reflexión o desarrollo…" className="w-full rounded-xl px-4 py-3 text-sm outline-none" style={{ background: "var(--surface-2)", border: "1px solid var(--border-strong)", color: "var(--text)" }} /><input type="url" value={enlace} onChange={(e) => setEnlace(e.target.value)} placeholder="Enlace a documento, repositorio o presentación (opcional)" className="w-full rounded-xl px-4 py-3 text-sm outline-none" style={{ background: "var(--surface-2)", border: "1px solid var(--border-strong)", color: "var(--text)" }} /><label className="flex cursor-pointer items-center gap-2 rounded-xl px-4 py-3 text-xs font-semibold" style={{ background: "var(--surface-2)", border: "1px dashed var(--border-strong)", color: "var(--text-muted)" }}><FileUp className="h-4 w-4" />{file ? file.name : initial?.archivo_path ? "Adjuntar un archivo nuevo (reemplaza el anterior)" : "Adjuntar PDF, Word, texto o imagen (máx. 10 MB)"}<input type="file" className="sr-only" accept=".pdf,.doc,.docx,.txt,image/png,image/jpeg" onChange={(e) => setFile(e.target.files?.[0] ?? null)} /></label>{message && <p className="text-xs" style={{ color: message.includes("correctamente") ? "var(--accent)" : "#dc2626" }}>{message}</p>}<button disabled={busy} className="btn-primary inline-flex items-center justify-center gap-2 rounded-xl px-5 py-3 text-xs disabled:opacity-60">{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}{busy ? "Enviando…" : initial ? "Actualizar entrega" : "Enviar entrega"}</button></div></form>;
}
